# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
workflows:
  version: 2
  build:
    jobs:
      - node6
      - node8
      - node9

version: 2
jobs:
  node6: &node6
    docker:
      - image: circleci/node:6

    working_directory: ~/repo

    steps:
      - run: node -v

      - run: npm -v

      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test
  node8:
    <<: *node6
    docker:
      - image: circleci/node:8

  node9:
    <<: *node6
    docker:
      - image: circleci/node:9
